FROM node:22-alpine AS builder

WORKDIR /app

COPY  package*.json ./

RUN  npm install --omit=dev

COPY . .


FROM gcr.io/distroless/nodejs22-debian12

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 5000

CMD ["server.js"]

